# Generated by Django 3.2.6 on 2024-07-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(blank=True, max_length=25, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.CharField(default=None, max_length=100, null=True)),
                ('cases', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('receipt_link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('budget_lead', models.ForeignKey(limit_choices_to=models.Q(models.Q(('category', 2), ('is_active', True), ('is_staff', True)), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='budget_lead', to='accounts.customeruser')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Operations', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date']},
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='down_payment',
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='fee_balance',
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='payment_fees',
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='student_bonus',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='activity_date',
        ),
        # migrations.RemoveField(
        #     model_name='transaction',
        #     name='department',
        # ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='clients_category',
            field=models.CharField(choices=[('DYC', 'Diaspora Youth Caucus'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='has_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Check', 'Check'), ('Cashapp', 'Cashapp'), ('Zelle', 'Zelle'), ('Venmo', 'Venmo'), ('Paypal', 'Paypal'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi_Weekly', 'Bi_Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Other', max_length=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_phone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Registration Fee', 'Registration Fee'), ('Contributions', 'Contributions'), ('Donations', 'Donations'), ('GC Application', 'GC Application'), ('Business', 'Business'), ('Tourism', 'Tourism'), ('Stocks', 'Stocks'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Inflow',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='finance.budgetcategory'),
        ),
    ]
