# Generated by Django 3.2.6 on 2023-04-25 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_information',
            name='down_payment',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(19.99), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
