# Generated by Django 3.2.6 on 2024-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budgetsubcategory_codabudget_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='department',
        ),
    ]
