# Generated by Django 3.2.6 on 2024-12-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_transaction_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='department',
        ),
    ]
