# Generated by Django 3.2.6 on 2024-07-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240722_1306'),
        ('marketing', '0002_auto_20240116_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ReplyMail',
            },
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='main.assets'),
        ),
    ]
