# Generated by Django 3.2.6 on 2023-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('sub_category', models.IntegerField(choices=[(0, 'No Selection'), (1, 'STUDENT VISA'), (2, 'BUSINESS VISA'), (3, 'WORK VISA'), (4, 'GREEN CARD'), (5, 'ASYLUM'), (6, 'OTHER')])),
                ('price', models.FloatField()),
            ],
        ),
    ]
