# Generated by Django 3.2.6 on 2024-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241203_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
