# Generated by Django 3.2.6 on 2024-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240711_1724'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='user',
    #         name='email',
    #         field=models.EmailField(max_length=254, unique=True),
    #     ),
    # ]
