# Generated by Django 3.2.6 on 2024-07-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240116_1040'),
        ('accounts', '0004_department'),
    ]

    operations = [
    ]
