# Generated by Django 3.2.6 on 2024-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240731_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_employee_contract_signed',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Bussines Training'), (2, 'Coda Staff Member'), (3, 'Jobsupport'), (4, 'Student'), (5, 'Investor'), (6, 'Vendor'), (7, 'General User')], default=999),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
