# Generated by Django 3.2.6 on 2024-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20241130_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Staff Member'), (6, 'General User')], default=999),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[(0, 'No selection'), (1, 'Full Time'), (2, 'Contractual'), (3, 'Agent'), (4, 'Short Term'), (5, 'Long Term'), (6, 'Current'), (7, 'Prospective'), (8, 'Other')], null=True),
        ),
    ]
