# Generated by Django 3.2.6 on 2024-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240731_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Bussines Training'), (2, 'Jobsupport'), (4, 'Investor'), (5, 'General User')], default=999),
        ),
    ]
