# Generated by Django 3.2.6 on 2024-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customeruser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_applicant',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is applicant'),
        ),
    ]
