# Generated by Django 3.2.6 on 2024-11-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Galleryimages',
    #     ),
    # ]
