# Generated by Django 3.2.6 on 2024-12-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galleryimage',
            new_name='Gallery_image',
        ),
    ]
