# Generated by Django 3.2.6 on 2024-12-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
