# Generated by Django 3.2.6 on 2024-11-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user.', max_length=100)),
                ('email', models.EmailField(help_text='Email address for correspondence.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the user (optional).', max_length=15, null=True)),
                ('message', models.TextField(help_text='Message or inquiry from the user.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was submitted.')),
                ('is_resolved', models.BooleanField(default=False, help_text='Flag to mark whether the query has been addressed.')),
            ],
        ),
    ]
