# Generated by Django 3.2.6 on 2024-06-18 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_description_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), blank=True, null=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
