# Generated by Django 3.2.6 on 2024-12-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_teams'),
        ('main', '0004_contactus'),
    ]

    operations = [
    ]
