# Generated by Django 3.2.6 on 2024-07-22 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='team',
            name='leadership',
            field=models.CharField(choices=[('Local', 'Local'), ('Global', 'Global')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('Governor', 'Governor'), ('Deputy Governor', 'Deputy Governor'), ('Regional Coordinator', 'Regional Coordinator'), ('Team Member', 'Team Member')], max_length=50),
        ),
    ]
