# Generated by Django 3.2.6 on 2024-08-06 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
        migrations.AddField(
            model_name='training',
            name='course_title',
            field=models.CharField( max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='training_title',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Export'), ('G2B', 'G2B'), ('B2B', 'B2B')], max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
