# Generated by Django 3.2.6 on 2024-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20240806_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='course_title',
            field=models.CharField(max_length=200),
        ),
    ]
