# Generated by Django 3.2.6 on 2024-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_training_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='link',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
