# Generated by Django 3.2.6 on 2024-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_subservice_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='link',
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
