# Generated by Django 3.2.6 on 2024-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20240807_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='url',
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='link',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
