# Generated by Django 3.2.6 on 2024-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20240807_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
