# Generated by Django 3.2.6 on 2024-08-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_investment_teammembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='title',
        ),
        migrations.AddField(
            model_name='investment',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
