# Generated by Django 3.2.6 on 2024-08-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240828_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='features',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
