# Generated by Django 3.2.6 on 2024-08-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20240831_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='buisness',
        ),
    ]
