# Generated by Django 3.2.6 on 2024-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20240831_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
