# Generated by Django 3.2.6 on 2024-10-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_business_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
